name: push
on: 
  push:
    branches:
      - main

env:
  VUE_APP_GOOGLE_ANALYTICS: ${{ secrets.VUE_APP_GOOGLE_ANALYTICS }}
  VUE_APP_GOOGLE_ADSENSE: ${{ secrets.VUE_APP_GOOGLE_ADSENSE }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./s3static
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn lint

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./s3static
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn --frozen-lockfile
      - run: yarn build 
